### ISSUE TITLE
Possible bug in OCaml syntax highlighting?

### ISSUE THREAD

**Issue by hammer** [textmate/ocaml.tmbundle#6]
Hey,

Some of the code in https://github.com/Chris00/ocaml-csv/blob/master/src/csv.mli is grayed out as a comment (e.g. val of_channel) when it's actually working code. I don't know enough about linguist to determine why this section is not being highlighted correctly, but I wanted to point it out in case someone wiser than me is watching these issues.

Thanks,
Jeff

**Comment by hammer** [comment]
(Originally filed downstream at https://github.com/github/linguist/issues/1985)

**Comment by infininight** [comment]
Corrected, thanks for the note.

This will be corrected in TextMate within a few hours, it will be included in linguist next time they update the grammars.
