### ISSUE TITLE
Can't install bundle

### ISSUE THREAD

**Issue by louisabraham** [textmate/ocaml.tmbundle#9]
I tried uninstalling and reinstalling, but the OCaml bundle does not work:
- I can't select the OCaml language
- I doesn't appear in the Edit Bundles menu.

The /Users/louisabraham/Library/Application Support/TextMate/Managed/Bundles/OCaml.tmbundle folder exists and looks fine.
Has anybody the same problem?

**Comment by infininight** [comment]
Sounds like something is wrong with the bundle index in general. Try the troubleshooting steps here:

https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

You can skip the preferences and tm_properties as they wouldn't be involved. If you need any more help you can email support:

http://macromates.com/support

**Comment by louisabraham** [comment]
Thank you, it's fixed!
